# Generated by Django 4.2 on 2023-07-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0006_pet_is_active'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sms_type', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.client')),
            ],
        ),
    ]
