# Generated by Django 4.2 on 2023-07-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smslogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslogs',
            options={'verbose_name_plural': 'SMS Logs'},
        ),
    ]
