# Generated by Django 4.2 on 2023-09-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_region_province_municipality_barangay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'verbose_name_plural': 'Barangays'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Provinces'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regions'},
        ),
    ]
