# Generated by Django 4.2 on 2023-05-19 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record_management', '0005_alter_client_gender'),
        ('services', '0003_alter_service_fee'),
        ('inventory', '0003_alter_product_quantity_on_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='BillingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_services', to='billing_management.billing')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_products', to='billing_management.billing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='products',
            field=models.ManyToManyField(through='billing_management.BillingProduct', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='billing',
            name='services',
            field=models.ManyToManyField(through='billing_management.BillingService', to='services.service'),
        ),
    ]
