# Generated by Django 4.2 on 2023-05-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_service_fee'),
        ('record_management', '0005_alter_client_gender'),
        ('inventory', '0002_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_products', to='billing_management.billing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='products',
            field=models.ManyToManyField(through='billing_management.BillingProduct', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='billing',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
