# Generated by Django 4.2 on 2023-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
