# Generated by Django 4.2 on 2023-05-19 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0002_alter_billingproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
