# Generated by Django 4.2 on 2023-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0003_billing_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='price_at_time_of_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
