# Generated by Django 4.2 on 2023-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0004_billingproduct_price_at_time_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingservice',
            name='price_at_time_of_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
