# Generated by Django 4.2 on 2023-09-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0005_billingservice_price_at_time_of_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingproduct',
            options={'verbose_name_plural': 'Billing Products'},
        ),
        migrations.AlterModelOptions(
            name='billingservice',
            options={'verbose_name_plural': 'Billing Services'},
        ),
    ]
