# Generated by Django 4.2 on 2023-09-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_product_original_product_and_more'),
        ('record_management', '0017_petmedicalprescription_pet_treatment'),
        ('billing_management', '0006_alter_billingproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='prescription_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_management.prescriptionmedicines'),
        ),
        migrations.AlterField(
            model_name='billingproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
