# Generated by Django 4.2 on 2023-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0009_alter_billing_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
