# Generated by Django 4.2 on 2023-10-28 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0010_alter_billing_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingservice',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
