# Generated by Django 4.2 on 2023-12-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0055_labresult_ispendinglabresult'),
        ('billing_management', '0011_billingservice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='treatments',
            field=models.ManyToManyField(blank=True, to='record_management.pettreatment'),
        ),
    ]
