# Generated by Django 4.2 on 2023-07-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0018_alter_service_remarks_delete_serviceremarks'),
        ('inventory', '0018_remove_product_original_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.producttype',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.service',),
        ),
    ]
