# Generated by Django 4.2 on 2023-07-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_services_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product Type'},
        ),
    ]
