# Generated by Django 4.2 on 2023-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(upload_to='images/pets/'),
        ),
    ]
