# Generated by Django 4.2 on 2023-07-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0010_alter_appointment_date'),
        ('record_management', '0007_group_user_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('treatment', models.CharField(choices=[('deworming', 'Deworming'), ('vaccination', 'Vaccination')], max_length=20)),
                ('medicine_used', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('next_treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment_management.appointment')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.pet')),
            ],
        ),
    ]
