# Generated by Django 4.2 on 2023-07-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0008_pethealthcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('lab_results', models.CharField(max_length=100)),
                ('findings', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnosis', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('medical_images', models.ImageField(upload_to='public/images/')),
                ('isActive', models.BooleanField(default=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.pet')),
                ('prescription', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='record_management.petmedicalprescription')),
            ],
        ),
    ]
