# Generated by Django 4.2 on 2023-07-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_product_original_product_and_more'),
        ('record_management', '0009_petmedicalprescription_petmedicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='form',
        ),
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='petmedicalprescription',
            name='strength',
        ),
        migrations.AddField(
            model_name='petmedicalprescription',
            name='date_prescribed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petmedicalprescription',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PrescriptionMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection')], max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('extra_medicine', models.CharField(max_length=100, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicines', to='inventory.product')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.petmedicalprescription')),
            ],
        ),
        migrations.AddField(
            model_name='petmedicalprescription',
            name='medicines',
            field=models.ManyToManyField(through='record_management.PrescriptionMedicines', to='inventory.product'),
        ),
    ]
