# Generated by Django 4.2 on 2023-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0010_remove_petmedicalprescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='extra_medicine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
