# Generated by Django 4.2 on 2023-07-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0011_alter_prescriptionmedicines_extra_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petmedicalprescription',
            options={'verbose_name_plural': 'Pet Medical Prescriptions'},
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_management.petmedicalprescription'),
        ),
    ]
