# Generated by Django 4.2 on 2023-07-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0012_alter_petmedicalprescription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pethealthcard',
            options={'verbose_name_plural': 'Pet Health Cards'},
        ),
        migrations.AlterModelOptions(
            name='petmedicalrecord',
            options={'verbose_name_plural': 'Pet Medical Records'},
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='findings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='lab_results',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='medical_images',
            field=models.ImageField(blank=True, null=True, upload_to='public/images/'),
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='petmedicalrecord',
            name='treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
