# Generated by Django 4.2 on 2023-09-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0013_alter_pethealthcard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionmedicines',
            options={'verbose_name_plural': 'Prescription Medicines'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='barangay',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='province',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='street',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup')], max_length=20),
        ),
    ]
