# Generated by Django 4.2 on 2023-09-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0010_alter_appointment_date'),
        ('record_management', '0014_alter_prescriptionmedicines_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateTimeField(auto_now=True)),
                ('lab_results', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_images', models.ImageField(blank=True, default='None', null=True, upload_to='public/images/')),
                ('isActive', models.BooleanField(default=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment_management.appointment')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.pet')),
            ],
            options={
                'verbose_name_plural': 'Pet Treatments',
            },
        ),
    ]
