# Generated by Django 4.2 on 2023-09-01 04:33

from django.db import migrations, models
import record_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0015_pettreatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettreatment',
            name='medical_images',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='public/images/', validators=[record_management.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
