# Generated by Django 4.2 on 2023-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0017_petmedicalprescription_pet_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='original_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
