# Generated by Django 4.2 on 2023-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0018_pet_original_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='health_card',
            field=models.BooleanField(default=False),
        ),
    ]
