# Generated by Django 4.2 on 2023-09-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0020_rename_health_card_pettreatment_isdeworm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicines',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
