# Generated by Django 4.2 on 2023-09-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0021_prescriptionmedicines_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicines',
            name='volume',
        ),
    ]
