# Generated by Django 4.2 on 2023-09-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0022_remove_prescriptionmedicines_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicines',
            name='form',
        ),
    ]
