# Generated by Django 4.2 on 2023-09-08 10:17

from django.db import migrations, models
import record_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0024_labresult_temporarylabresultimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarylabresultimage',
            name='image',
            field=models.ImageField(upload_to='public/images/', validators=[record_management.models.validate_image_extension]),
        ),
    ]
