# Generated by Django 4.2 on 2023-09-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0025_alter_temporarylabresultimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarylabresultimage',
            options={'verbose_name_plural': 'Temporary Lab Result Images'},
        ),
    ]
