# Generated by Django 4.2 on 2023-09-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0026_alter_temporarylabresultimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
