# Generated by Django 4.2 on 2023-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0027_alter_prescriptionmedicines_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicines',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
