# Generated by Django 4.2 on 2023-09-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0028_alter_prescriptionmedicines_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
