# Generated by Django 4.2 on 2023-09-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0032_remove_pettreatment_remainingcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='cycle_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
