# Generated by Django 4.2 on 2023-09-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0033_pettreatment_cycle_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='cycle_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
