# Generated by Django 4.2 on 2023-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0034_pettreatment_cycle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='total_cycle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
