# Generated by Django 4.2 on 2023-09-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0036_rename_hasappointmentcycle_pettreatment_hasmultiplecycles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentcycle',
            options={'verbose_name_plural': 'Pet Treatment Cycles'},
        ),
        migrations.AddField(
            model_name='pettreatment',
            name='appointment_cycles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettreatment',
            name='cycles_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
