# Generated by Django 4.2 on 2023-09-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0037_alter_treatmentcycle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='isHealthCard',
            field=models.BooleanField(default=False),
        ),
    ]
