# Generated by Django 4.2 on 2023-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0038_pettreatment_ishealthcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
