# Generated by Django 4.2 on 2023-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0039_client_isbanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='picture',
        ),
        migrations.AddField(
            model_name='pet',
            name='_picture',
            field=models.ImageField(blank=True, null=True, upload_to='public/images/'),
        ),
    ]
