# Generated by Django 4.2 on 2023-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0040_remove_pet_picture_pet__picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='_picture',
        ),
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='public/images/'),
        ),
    ]
