# Generated by Django 4.2 on 2023-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0041_remove_pet__picture_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='public/images/'),
        ),
    ]
