# Generated by Django 4.2 on 2023-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0044_labresult_normal_range_labresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ban_reason',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
