# Generated by Django 4.2 on 2023-11-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0045_client_ban_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_test_unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
