# Generated by Django 4.2 on 2023-12-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0047_alter_laboratorytests_options_client_iswalkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorytests',
            name='lab_test_unit_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
