# Generated by Django 4.2 on 2023-12-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0048_laboratorytests_lab_test_unit_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorytests',
            old_name='lab_test_unit_description',
            new_name='lab_test_description',
        ),
    ]
