# Generated by Django 4.2 on 2023-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0050_laboratorytests_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='lab_tests',
            field=models.ManyToManyField(blank=True, to='record_management.laboratorytests'),
        ),
    ]
