# Generated by Django 4.2 on 2023-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0051_pettreatment_lab_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettreatment',
            name='isPendingLabResults',
            field=models.BooleanField(default=False),
        ),
    ]
