# Generated by Django 4.2 on 2023-12-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0052_pettreatment_ispendinglabresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettreatment',
            name='isPendingLabResults',
        ),
        migrations.RemoveField(
            model_name='pettreatment',
            name='lab_tests',
        ),
    ]
