# Generated by Django 4.2 on 2023-12-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0053_remove_pettreatment_ispendinglabresults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettreatment',
            name='cycles_remaining',
        ),
    ]
