# Generated by Django 4.2 on 2023-12-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0054_remove_pettreatment_cycles_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='isPendingLabResult',
            field=models.BooleanField(default=False),
        ),
    ]
