# Generated by Django 4.2 on 2023-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('deworming', 'Deworming'), ('vaccination', 'Vaccination'), ('checkup', 'Check-up'), ('procedure', 'Procedure'), ('other', 'Other')], max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.CharField(choices=[('without_medicine', 'Without Medicine'), ('with_medicine', 'With Medicine')], max_length=20)),
            ],
        ),
    ]
