# Generated by Django 4.2 on 2023-05-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
