# Generated by Django 4.2 on 2023-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='control_number',
            field=models.IntegerField(default=1),
        ),
    ]
