# Generated by Django 4.2 on 2023-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
