# Generated by Django 4.2 on 2023-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='previous_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
