# Generated by Django 4.2 on 2023-06-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_previous_version_service_updated_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_version',
        ),
    ]
