# Generated by Django 4.2 on 2023-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_previous_version_service_updated_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='original_service_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
