# Generated by Django 4.2 on 2023-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_original_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='previous_version',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_version',
            field=models.CharField(blank=True, null=True),
        ),
    ]
