# Generated by Django 4.2 on 2023-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_service_original_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='original_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_version',
        ),
        migrations.AddField(
            model_name='service',
            name='changes_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
