# Generated by Django 4.2 on 2023-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_service_original_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='control_number',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
