# Generated by Django 4.2 on 2023-07-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_service_remarks_delete_serviceremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Remark',
                'verbose_name_plural': 'Service Remarks',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='remarks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.serviceremarks'),
        ),
    ]
