# Generated by Django 4.2 on 2023-09-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_service_remarks_delete_serviceremarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='remarks',
        ),
    ]
