# Generated by Django 4.2 on 2023-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_service_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
