# Generated by Django 4.2 on 2023-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_service_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='job_for',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('veterinary technician', 'Veterinary Technician'), ('veterinary assistant', 'Veterinary Assistant')], default='doctor', max_length=50),
        ),
    ]
