# Generated by Django 4.2 on 2023-05-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_on_stock', models.IntegerField()),
                ('type', models.CharField(choices=[('tablets', 'Tablets'), ('syrups', 'Syrups'), ('injections', 'Injections'), ('ointments', 'Ointments'), ('capsules', 'Capsules')], default='tablets', max_length=50)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('critical_level', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
