# Generated by Django 4.2 on 2023-05-20 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_quantity_on_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_on_stock',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
