# Generated by Django 4.2 on 2023-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
