# Generated by Django 4.2 on 2023-06-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
