# Generated by Django 4.2 on 2023-07-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_producttype_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='original_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
