# Generated by Django 4.2 on 2023-07-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_product_original_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='previous_version',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_version',
            field=models.CharField(blank=True, null=True),
        ),
    ]
