# Generated by Django 4.2 on 2023-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_product_previous_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='changes_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
