# Generated by Django 4.2 on 2023-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_changes_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_version',
        ),
        migrations.AlterField(
            model_name='product',
            name='batch_number',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='changes_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
