# Generated by Django 4.2 on 2023-09-03 04:46

from django.db import migrations

def create_product_type_if_not_exists(apps, schema_editor):
    ProductType = apps.get_model('inventory', 'ProductType')
    if not ProductType.objects.filter(name="Medicines").exists():
        ProductType.objects.create(name="Medicines")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20230903_1242'),
    ]

    operations = [
        migrations.RunPython(create_product_type_if_not_exists)
    ]
