# Generated by Django 4.2 on 2023-09-03 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20230903_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
