# Generated by Django 4.2 on 2023-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('gel', 'Gel'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('lotion', 'Lotion'), ('injection', 'Injection'), ('suspension', 'Suspension'), ('drop', 'Drop'), ('spray', 'Spray'), ('powder', 'Powder'), ('granule', 'Granule'), ('liquid', 'Liquid'), ('paste', 'Paste'), ('spot-on', 'Spot-On Treatment'), ('chew', 'Chewable'), ('pellet', 'Pellet'), ('bolus', 'Bolus'), ('feed_additive', 'Feed Additive'), ('oral_solution', 'Oral Solution'), ('ear_drop', 'Ear Drop'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
