# Generated by Django 4.2 on 2023-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_product_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
