# Generated by Django 4.2 on 2023-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_product_manufacturer_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_type_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
