# Generated by Django 4.2 on 2023-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_producttype_product_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume_unit',
            field=models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('mg', 'Milligram (mg)'), ('mL', 'Milliliter (mL)'), ('L', 'Liter (L)'), ('piece', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('set', 'Set')], default='piece', max_length=20),
        ),
    ]
