# Generated by Django 4.2 on 2023-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_product_volume_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='form',
            field=models.CharField(choices=[('', 'Select Form'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('granule', 'Granule'), ('chew', 'Chewable'), ('pellet', 'Pellet'), ('injection', 'Injection'), ('liquid', 'Liquid'), ('feed_additive', 'Feed Additive'), ('oral_solution', 'Oral Solution'), ('ear_drop', 'Ear Drop'), ('spot-on', 'Spot-On Treatment'), ('gel', 'Gel'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('lotion', 'Lotion'), ('suspension', 'Suspension'), ('drop', 'Drop'), ('spray', 'Spray'), ('powder', 'Powder'), ('paste', 'Paste'), ('bolus', 'Bolus'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_unit',
            field=models.CharField(choices=[('', 'Select Unit'), ('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('mL', 'Milliliter (mL)'), ('L', 'Liter (L)'), ('piece', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('set', 'Set')], default='piece', max_length=20),
        ),
    ]
