# Generated by Django 4.2 on 2023-10-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_product_has_new_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
