# Generated by Django 4.2 on 2023-07-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0010_service_original_service_type'),
        ('record_management', '0006_pet_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfTheDay', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rebook', 'Rebook'), ('cancelled', 'Cancelled'), ('done', 'Done')], max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.client')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.pet')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
