# Generated by Django 4.2 on 2023-07-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
