# Generated by Django 4.2 on 2023-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0004_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaximumAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_appointments', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Maximum Appointment',
                'verbose_name_plural': 'Maximum Appointments',
            },
        ),
    ]
