# Generated by Django 4.2 on 2023-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0005_maximumappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maximumappointment',
            name='max_appointments',
            field=models.IntegerField(default=8),
        ),
    ]
