# Generated by Django 4.2 on 2023-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0006_alter_maximumappointment_max_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slots', models.IntegerField(default=8)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Date Slot',
                'verbose_name_plural': 'Date Slots',
            },
        ),
    ]
