# Generated by Django 4.2 on 2023-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0011_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateslot',
            name='timeOfTheDay',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('whole_day', 'Whole Day')], default='whole_day', max_length=10),
        ),
    ]
