# Generated by Django 4.2 on 2023-09-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0013_alter_dateslot_timeoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
