# Generated by Django 4.2 on 2023-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0014_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateslot',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='dateslot',
            name='timeOfTheDay',
        ),
        migrations.AddField(
            model_name='dateslot',
            name='afternoon_slots',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='dateslot',
            name='morning_slots',
            field=models.IntegerField(default=4),
        ),
    ]
