# Generated by Django 4.2 on 2023-11-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0016_smstemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'verbose_name': 'SMS Template', 'verbose_name_plural': 'SMS Templates'},
        ),
    ]
