# Generated by Django 4.2 on 2023-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0017_alter_smstemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
