# Generated by Django 4.2 on 2023-11-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0019_rename_remarks_appointment_symtomps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='symtomps',
            field=models.CharField(blank=True, null=True),
        ),
    ]
