# Generated by Django 4.2 on 2023-11-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0020_alter_appointment_symtomps'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='one_hour_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='today_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
